echo "ADDCAR TEAM: AAA, CAR: 1, SPEED: 150, CONSUMPTION: 0.1, RELIABILITY: 87" > COMMAND_PIPE
sleep 0.01
echo "ADDCAR TEAM: AAA, CAR: 2, SPEED: 120, CONSUMPTION: 0.2, RELIABILITY: 95" > COMMAND_PIPE
sleep 0.01
echo "ADDCAR TEAM: WEE, CAR: 3, SPEED: 200, CONSUMPTION: 1, RELIABILITY: 70" > COMMAND_PIPE
sleep 0.01
echo "ADDCAR TEAM: BBB, CAR: 4, SPEED: 170, CONSUMPTION: 0.3, RELIABILITY: 75" > COMMAND_PIPE
sleep 0.01
echo "START RACE!" > COMMAND_PIPE
