echo "ADDCAR TEAM: AAA, CAR: 6, SPEED: 100, CONSUMPTION: 5, RELIABILITY: 95" > COMMAND_PIPE
sleep 0.1
echo "ADDCAR TEAM: AAA, CAR: 5, SPEED: 120, CONSUMPTION: 3, RELIABILITY: 90" > COMMAND_PIPE
sleep 0.1
echo "ADDCAR TEAM: AAA, CAR: 4, SPEED: 200, CONSUMPTION: 4, RELIABILITY: 74" > COMMAND_PIPE
sleep 0.1
echo "ADDCAR TEAM: AAA, CAR: 3, SPEED: 200, CONSUMPTION: 6, RELIABILITY: 60" > COMMAND_PIPE
sleep 0.1
echo "ADDCAR TEAM: AAA, CAR: 2, SPEED: 300, CONSUMPTION: 2, RELIABILITY: 70" > COMMAND_PIPE
sleep 0.1
echo "ADDCAR TEAM: AAA, CAR: 1, SPEED: 250, CONSUMPTION: 1, RELIABILITY: 83" > COMMAND_PIPE
sleep 0.1
echo "ADDCAR TEAM: WEE, CAR: 7, SPEED: 300, CONSUMPTION: 0.01, RELIABILITY: 70" > COMMAND_PIPE
sleep 0.1
echo "ADDCAR TEAM: BBB, CAR: 8, SPEED: 250, CONSUMPTION: 0.02, RELIABILITY: 83" > COMMAND_PIPE
sleep 0.1
echo "START RACE!" > COMMAND_PIPE
