echo "ADDCAR TEAM: AAA, CAR: 6, SPEED: 100, CONSUMPTION: 0.03, RELIABILITY: 95" > COMMAND_PIPE
sleep 1
echo "ADDCAR TEAM: BBB, CAR: 5, SPEED: 120, CONSUMPTION: 0.04, RELIABILITY: 90" > COMMAND_PIPE
sleep 1
echo "ADDCAR TEAM: BBB, CAR: 4, SPEED: 200, CONSUMPTION: 0.02, RELIABILITY: 74" > COMMAND_PIPE
sleep 1
echo "ADDCAR TEAM: AAA, CAR: 3, SPEED: 200, CONSUMPTION: 0.05, RELIABILITY: 60" > COMMAND_PIPE
sleep 1
echo "ADDCAR TEAM: CCC, CAR: 2, SPEED: 300, CONSUMPTION: 0.02, RELIABILITY: 70" > COMMAND_PIPE
sleep 1
echo "ADDCAR TEAM: WEEE, CAR: 1, SPEED: 250, CONSUMPTION: 0.02, RELIABILITY: 83" > COMMAND_PIPE
sleep 1
echo "START RACE!" > COMMAND_PIPE
