echo "ADDCAR TEAM: AAA, CAR: 10, SPEED: 3300, CONSUMPTION: 3, RELIABILITY: 95" > ../COMMAND_PIPE
echo "ADDCAR TEAM: BBB, CAR: 20, SPEED: 3400, CONSUMPTION: 3, RELIABILITY: 95" > ../COMMAND_PIPE
echo "ADDCAR TEAM: BBB, CAR: 20, SPEED: 4000, CONSUMPTION: 5.5, RELIABILITY: 80" > ../COMMAND_PIPE
echo "ADDCAR TEAM: BBB, CAR: 21, SPEED: 4000, CONSUMPTION: 5.5, RELIABILITY: 80" > ../COMMAND_PIPE
echo "ADDCAR TEAM: BBB, CAR: 22, SPEED: 3800, CONSUMPTION: 3.8, RELIABILITY: 80" > ../COMMAND_PIPE
echo "START RACE!" > ../COMMAND_PIPE
echo "ADDCAR TEAMS: CCC" > ../COMMAND_PIPE
